export const ActionTypes = {
    SET_CONTROL_VIEW: 'SET_CONTROL_VIEW',
    SET_MISSION_VIEW: 'SET_MISSION_VIEW',
    OPEN_COLLISION_REPORT: 'OPEN_COLLISION_REPORT',
    CLOSE_COLLISION_REPORT: 'CLOSE_COLLISION_REPORT',
    SET_MISSION_CONTROL: 'SET_MISSION_CONTROL',
    SET_COLLISIONS_DETECTED: 'SET_COLLISIONS_DETECTED',
    CLEAR_DETECTIONS: 'CLEAR_DETECTIONS',
    SET_OFF_WORLD_PATH_DETECTED: 'SET_OFF_WORLD_PATH_DETECTED'
}
