const CONTROL = 'CONTROL';
const MISSION = 'MISSION';
const CARDINAL_POSITIONS = [0, 90, 180, -90];
const SPEED = 15;
const INSTRUCTIONS = 'INSTRUCTIONS';
const COORDINATES = 'COORDINATES';
const COMMANDS = 'COMMANDS';
const POSITION = 'POSITION';


export {
    CONTROL,
    MISSION,
    CARDINAL_POSITIONS,
    SPEED,
    INSTRUCTIONS,
    COMMANDS,
    COORDINATES,
    POSITION
};
